Add category store
hallowelt/mwstake-mediawiki-component-commonwebapis pull request #14
Opened 2024-03-04 08:33 UTC by it-spiderman

2024-03-04 09:03 UTC, osnard requested changes

2024-03-04 09:03 UTC, osnard commented on bootstrap.php
> +define( 'MWSTAKE_MEDIAWIKI_COMPONENT_COMMONWEBAPIS_VERSION', '2.0.15' );
Looks more like a minor-level change

2024-03-04 09:03 UTC, osnard commented on src/Data/CategoryQueryStore/PrimaryDataProvider.php
> +			$field = "REPLACE( LOWER( CONVERT(cl_to USING utf8mb4) ), '_', ' ' )";
Would there be a way of doing this DBMS agnostic?

2024-03-04 11:08 UTC, it-spiderman commented on src/Data/CategoryQueryStore/PrimaryDataProvider.php
> +			$field = "REPLACE( LOWER( CONVERT(cl_to USING utf8mb4) ), '_', ' ' )";
using index now

2024-03-26 11:58 UTC, it-spiderman commented on bootstrap.php
> +define( 'MWSTAKE_MEDIAWIKI_COMPONENT_COMMONWEBAPIS_VERSION', '2.0.15' );
why? it just adds more of  the same, not changing anything

2024-03-26 12:09 UTC, merged